export const keyboard = [
  { label: 'й' },
  { label: 'ц' },
  { label: 'у' },
  { label: 'к' },
  { label: 'е' },
  { label: 'н' },
  { label: 'г' },
  { label: 'ш' },
  { label: 'щ' },
  { label: 'з' },
  { label: 'х' },
  { label: 'ъ' },

  { label: 'ф', styleType: 'marginLeft' },
  { label: 'ы' },
  { label: 'в' },
  { label: 'а' },
  { label: 'п' },
  { label: 'р' },
  { label: 'о' },
  { label: 'л' },
  { label: 'д' },
  { label: 'ж' },
  { label: 'э' },

  { label: '←', styleType: 'large white' },
  { label: 'я' },
  { label: 'ч' },
  { label: 'с' },
  { label: 'м' },
  { label: 'и' },
  { label: 'т' },
  { label: 'ь' },
  { label: 'б' },
  { label: 'ю' },
  { label: '✓', styleType: 'large yellow' },
];
